#!/bin/sh

###########################################################################################################
#######  'photoName' is just a place holder in order to take the picture then delete the local file #######
###########################################################################################################

# uncomment for dslr use
#gphoto2 --capture-image-and-download --filename photoName

# uncomment for webcam use 
fswebcam --no-banner -d /dev/video0 -r 960x720 photoName 

# uploads the file and gets the saved file's name
getphoto=$(curl --upload-file photoName http://10.1.2.117:8080/)

# deletes photo from pi
rm photoName

# return name of photo to node
echo $getphoto
